### ISSUE TITLE
libusb_control_transfer() return value misinterpreted

### ISSUE THREAD

**Issue by unruhschuh** [TiltedPlacitan/SoundcraftNotepad12FX#1]
Hi, the return value of libusb_control_transfer() is the number of transfered bytes (8 in this case) or an error code LIBUSB_ERROR_* which are < 0. Checking it for != 0 causes the program to exit(1) every time.

https://github.com/TiltedPlacitan/SoundcraftNotepad12FX/blob/2b5c720658836d472aa4115251eb7bb4e648b584/notepad-12fx-source.c#L138C9-L138C32

**Comment by TiltedPlacitan** [comment]
Thank you for pointing this out.  Sorry it took so long for me to notice.  It's been fixed.
